/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { RigidBody, CuboidCollider } from "@react-three/rapier";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/star.gltf`

export function Star(props) {

    const { nodes, materials } = useGLTF(link);

    const [collected, setCollected] = useState(false);

    const handleCollision = (e) => {
        const otherData = e.other?.rigidBodyObject?.userData
        if (otherData?.isPlayer) {
            setCollected(true)
        }
    }

    const starRef = useRef();

    // Rotation animation
    useFrame(() => {
        if (starRef.current) {
            starRef.current.rotation.z += 0.005;
        }
    });

    // Bobbing animation
    useFrame(({ clock }) => {
        if (starRef.current) {
            starRef.current.position.y =
                Math.sin(clock.elapsedTime) * 0.2;
        }
    });

    return (
        <RigidBody
            type="fixed"
            position={props.position}
            sensor
            userData={{ isStar: true }}
            onIntersectionEnter={handleCollision}
        >
            <CuboidCollider args={[0.5, 1, 0.5]} />
            {!collected && (
                <group scale={props.scale} dispose={null}>
                    <mesh
                        ref={starRef}
                        castShadow
                        receiveShadow
                        geometry={nodes.star.geometry}
                        material={materials["Yellow.030"]}
                        rotation={[Math.PI / 2, 0, 0]}
                    />
                </group>
            )}
        </RigidBody>
    );
}

useGLTF.preload(link);
